# register
POST /api/register
Host: localhost
Content-Type: application/json

{
    "name": "aaa",
    "email": "aaa@aaa",
    "password": "11111111"
}

###

# login
POST /api/login
Host: localhost
Content-Type: application/json

{
    "email": "oyuki.gamer@gmail.com",
    "password": "ikuya512"
}

###

# user
GET /api/user
Host: localhost
Content-Type: application/json
Authorization: Bearer 7|9bJXiSPXUkAQRToyi1w4B0gEiSihL0gFkl3YM8tz
###

# clubs request
POST /api/request
Host: localhost
Content-Type: application/json
Authorization: Bearer 8|KLFxx2YoAV1O70gDI9iff4p07jKEwYcHECGHQjEj

{
    "name": "oyuki",
    "unique_name": "api",
    "password": "apiapiapi"
}

###
# clubs index
GET /api/clubs
Host: localhost
Content-Type: application/json
Authorization: Bearer 7|9bJXiSPXUkAQRToyi1w4B0gEiSihL0gFkl3YM8tz

###

# clubs store
POST /api/clubs
Host: localhost
Content-Type: application/json
Authorization: Bearer 4|N6DGSvPWPmGwU2BTsLBCD9xb05VPbtEqVlQI6xSl

{
    "name": "API中学校",
    "unique_name": "apischool",
    "password": "password",
    "confirm": "password"
}

###


# clubs show
GET /api/clubs/1
Host: localhost
Content-Type: application/json
Authorization: Bearer 7|9bJXiSPXUkAQRToyi1w4B0gEiSihL0gFkl3YM8tz
###


# clubs update
PATCH /api/clubs/3
Host: localhost
Content-Type: application/json
Authorization: Bearer 5|IjZiocH38QXcjurAYMRJiSh0E4RKAUzkbHFIYXb0

{
    "name": "api中学校",
    "unique_name": "api",
    "password": "apiapiapi",
    "confirm": "apiapiapi"
}
###

# clubs plans index
GET /api/clubs/3/2021/11
Host: localhost
Content-Type: application/json
Authorization: Bearer 6|vm5w5jT2s7cYpTzdMJkoYagZnAfETUpoMpJxAyda

###

#clubs plans store
POST /api/clubs/3/plans
Host: localhost
Content-Type: application/json
Authorization: Bearer 7|9bJXiSPXUkAQRToyi1w4B0gEiSihL0gFkl3YM8tz

{
    "name" : "apistore",
    "meeting_time" : "2021-11-22 10:00:00",
    "dissolution_time" : "2021-11-22 15:00:00",
    "place" : "ここ",
    "remarks" : "備考は備考だ",
    "public" : {
        "0" : "12"
    }
}

###

#clubs plans threads store
POST /api/clubs/3/plans/8/threads
Host: localhost
Content-Type: application/json
Authorization: Bearer 9|jTM0OwjkdnpCDKDOH41OplgvhJoXstF7pjoWpkbz

{
    "body" : "でもリアルタイム更新じゃないんだよね"
}

###
